### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by soggie** [dsimard/ready.js#11]
$npm install ready.js

Then in my local folder, I did:

$readyjs resource-widget.js resource-widget.min.js

I'm pretty sure I'm running on the same directory as my files are, but nothing popped up. This is the message that came out:

WARNING : No files to process

What's wrong?

**Comment by dsimard** [comment]
You can't do it for a single file right now. You have to use a complete folder. I will try to add the options for a single file.

**Comment by dsimard** [comment]
In fact, it is created to jslint and compile a folder of javascript files, not a single file. I won't add this feature for now.
