### ISSUE TITLE
Feature request: jshint integration

### ISSUE THREAD

**Issue by kilianc** [dsimard/ready.js#14]
What about integrating [jshint](https://github.com/jshint/jshint)? jslint is too aggressive sometimes...

**Comment by dsimard** [comment]
I think it's too aggressive sometimes too but there are options you can set. I will still take a look at jshint!

**Comment by dsimard** [comment]
ready.js v2.0.0 is out and I switched to jshint

**Comment by kilianc** [comment]
awesome!
