### ISSUE TITLE
Switch from Google Closure Compiler to Uglify-js

### ISSUE THREAD

**Issue by joshsmith** [dsimard/ready.js#15]
Just a suggestion, but I would love this change for two reasons:

1) Google's Closure Compiler has made some funky and unnecessary alterations to some of my JavaScript, and has been reported by others as being randomly buggy in certain situations.

2) Uglify is more performant than Closure Compiler.

Thanks!

**Comment by dsimard** [comment]
ready.js v2.0.0 is out and I switched to Uglify
