### ISSUE TITLE
[feature request] --no-aggregate option and exclude node_modules option

### ISSUE THREAD

**Issue by kazuyukitanimura** [dsimard/ready.js#16]
Can you please add  --no-aggregate option?
In addition, is there an easy way to exclude everything under node_modules directory?

Thanks

**Comment by dsimard** [comment]
Hi, I added the no-aggregate option. 

There is no easy way right now to exclude a whole directory. I will dig into this as soon as possible.

Thanks!

**Comment by kazuyukitanimura** [comment]
Awesome!!!!

Many thanks!

**Comment by kazuyukitanimura** [comment]
I noticed /bin/ready.js still logs out the message "aggregating..." even with the new --no-aggregation option.

This is just a minor point though.

Thank you again for the awesome project!

**Comment by dsimard** [comment]
Hi Kazuyuki,
it should be solved now. I wrote a test for it but let me know if it works for you! The new version is 2.0.2.

**Comment by kazuyukitanimura** [comment]
It perfectly worked as I expected! Thanks! I love this project.
