### ISSUE TITLE
Discussion topic: New ready.js approach 

### ISSUE THREAD

**Issue by kilianc** [dsimard/ready.js#17]
Hi @dsimard, before starting to build my own tool, I want to talk with you about a radical change of ready js.
Hope you will understand my goals reading the `confing.json` below

``` js
{
  "targets": [{
      "output_file": "public/js/my-awesome-lib-compiled.js",
      "source": "js/lib/my-awesome-lib.js",
      "syntax_check": {
        "indent": 2,
        "boss": true,
        "browser": true
      },
      "compile": true,
    },{
      "output_file": "public/js/application-min.js",
      "source": [
        "js/lib/mootools-core-1.4.2-full-nocompat.js --check-syntax",
        "js/lib/mootools-more-1.4.0.1.js --check-syntax",
        "public/js/my-awesome-lib-compiled.js",
        "js/application.js --check-syntax --compile",
      ],
      "syntax_check": "default",
      "compile": true,
  }],
  "defaults": {
    "syntax_check": {
      "indent": 2,
      "boss": true,
      "browser": true,
      "curly": true,
      "debug": true,
      "devel": true,
      "eqeqeq": true,
      "es5": true,
      "expr": true,
      "mootools": true,
      "newcap": true,
      "passfail": true,
      "triling": true,
      "undef": true,
      "white": true
    }
  }
}
```

**Comment by dsimard** [comment]
Hi,
I understand what you mean and I guess it would be feasible.

There are two things to look for. First, having the jshint options set inside the files as you can see : http://www.jshint.com/about/ . This would avoid defining them for ready.js only as it would work vanilla with jshint.

Also, I would see a config.json that would look like this to avoid changing the format of the config.json :

```
{ 
  src : "./", 
  dest : "./compiled", 
  compiledExtension : "min", 
  analyse : true,
  compile : true,
  keepCompiled : false, 
  aggregateTo : "all.js", 
  order : [], 
  exclude : [], 
  recursive : true,
  test : false,
  analysisOptions: {}
  /* Overrides are set here. Each option overrides the one set above */
  overrides : {
    src : ["./js/lib/mootools-core-1.4.2-full-nocompat.js",
      "js/lib/mootools-more-1.4.0.1.js"],
    dest : "./public/js/application-min.js", 
    compiledExtension : "xyz", 
    analysisOptions: {mootools: true, 
      eqeqeq: true, /* ... other options */}
  }
}
```

I don't have time to work on this right now but I could help you with the code if you want to fork it.

Thanks!

**Comment by kilianc** [comment]
The problem with your json (is not a valid json anymore, you need to quote the keys) proposal is that you can't control the flow.
I want to manage around each file If I want to check/compile it ("--check-syntax --compile").
Second thing, I guess you meant that overrides is an Array and not just a single object right?

I would not worry about a breaking change, we can bump the major release.

The point here is, if you want just a minifier automated bot, that copiles each files into his own "-min" version,
you can do something like this:

``` javascript
{
  "targets": [{
      "output_file": "public/js/{filename}-min.js",
      "source": "js/lib/*.js",
      "syntax_check": {
        "indent": 2,
        "boss": true,
        "browser": true
      },
      "compile": true,
    }
}
```

And you can still control the aggregation chain.
We deal every day with third parties scripts, mixed with our code ext.
Personally I need more flexibility.

Totally agree with the jshint thing, but this is a common "teammate" issue.
You need a common check for all the files, and it avoids to repeat the conf for each file.
It's very crappy to mixup jshint and my code in the same file.
I think we can use the `.jshint` file pattern instead, versionable and portable. Maybe I need more flexibility than this but I will find a way for inherited jshint configuration.

It could be:

``` javascript

"targets": [{
...
  "syntax_check": ".jshint",
...
 }

```

**Comment by kilianc** [comment]
Another big point is the check/compile/aggregation control for each file.

``` javascript
exclude : [], // Files that are not compiled but still aggregated
```

This is the only option I found, but what if I need to skip the check of some files? What if I need to skip a file for the aggregation? It forces me to change my project folder structure, and I still have only a single aggregation point (partially resolved with your proposal).
Its a strange behavior to have a src and an order array imho.

I don't want to be rude, I like you project and I believe that a lot of people need something like this.

**Comment by dsimard** [comment]
Hi,

>  I guess you meant that overrides is an Array and not just a single object right?

right

> I would not worry about a breaking change, we can bump the major release.

I just can't do that. It would require that everyone using previous versions couldn't update unless they go through a long process of editing all their config files. I know that's what major versions are for but it just wouldn't be a good long-term decision for the project. 

> I think we can use the .jshint file pattern instead, versionable and portable. Maybe I need more flexibility than this but I will find a way for inherited jshint configuration.

That is a great idea, I wasn't even aware that `.jshint` existed!

Here is my proposition for your need. I didn't validate the json and there are things that will change eventually but this is the big picture :

```
{ 
  src : "./", 
  dest : "public/js/my-awesome-lib-compiled.js", 
  compiledExtension : "min", 
  analyse : true,
  compile : true,
  aggregate: false, // new option that will be in 2.0.2
  order : [], 
  exclude : [], 
  recursive : true,
  analysisOptions: {
    "indent" : 2 // all defaults here
  }
  /* Overrides are set here. Each option overrides the one set above */
  overrides : [
    {
      files:["js/lib/mootools-core-1.4.2-full-nocompat.js", "js/lib/mootools-more-1.4.0.1.js", "js/application.js"],
      dest : "public/js/application-min.js",
      analysisOptions : {
        "indent": 2,
        "boss": true
      },
    },
    {
      files:["public/js/my-awesome-lib-compiled.js"],
      analyse: false,
      compile: false,
      aggregate: false
    }
  ]
}
```

**Comment by kilianc** [comment]
I understand how annoying could be a drastic API / JSON change.
I still need something more closer to what I have in mind, so I think I am going to start my own dev tool.

Anyway I am glad about our thoughts exchange :)

P.S. totally sad about the naming, I like ready.js :)

**Comment by dsimard** [comment]
Thanks for taking the time to write me.

> I still need something more closer to what I have in mind, so I think I am going to start my own dev tool.

Let me know as soon as you're starting your project, I will follow it.

> P.S. totally sad about the naming, I like ready.js :)

That's funny because I'm not too crazy about it...

Thanks!
