### ISSUE TITLE
"order" option not affecting aggregation order

### ISSUE THREAD

**Issue by averyvery** [dsimard/ready.js#3]
The final aggregation doesn't seem to be respecting the "order" config option for me...

I enter:

<pre>
{ 
  src : "themes/refresh/js/",
  dest : "themes/refresh/js/minified",
  minifiedExtension : "min",
  order:[
    "jquery.js", 
    "jquery.ui.js",
    "jquery.animate_rotate_scale.js",
    "jquery.carousel.js",
    "jquery.css_transform.js",
    "jquery.equal_columns.js",
    "jquery.js",
    "jquery.simpleSlideshow.js",
    "lettering.js",
    "application.js"
  ],
  runGCompiler : true, // If should run GoogleCompiler
  runJsLint : false, // If should run JsLint
  debug: true,
  aggregateTo : "themes/refresh/js/all.min.js" // Which file to aggregate all javascript files
}
</pre>

...but mysteriously, equal_columns, simpleSlideshow, and lettering come out first in the resulting file. Any ideas?

**Comment by averyvery** [comment]
Here's the debug:

<pre>
Exec with config
Truncated /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Aggregate file : /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Aggregate file : /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Write compiled file to /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.equal_columns.min.js
Aggregate /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.equal_columns.min.js to /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Write compiled file to /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/lettering.min.js
Aggregate /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/lettering.min.js to /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Write compiled file to /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.simpleSlideshow.min.js
Aggregate /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.simpleSlideshow.min.js to /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Write compiled file to /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.animate_rotate_scale.min.js
Aggregate /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.animate_rotate_scale.min.js to /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Write compiled file to /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.css_transform.min.js
Aggregate /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.css_transform.min.js to /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Write compiled file to /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/application.min.js
Aggregate /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/application.min.js to /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Write compiled file to /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.carousel.min.js
Aggregate /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.carousel.min.js to /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
Write compiled file to /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.min.js
Aggregate /Applications/MAMP/htdocs/refresh/themes/refresh/js/minified/jquery.min.js to /Applications/MAMP/htdocs/refresh/themes/refresh/js/all.min.js
</pre>

**Comment by averyvery** [comment]
Apologies, it looks like I was using an outdated version. I'll work with the new one and see if the issue continues.

**Comment by averyvery** [comment]
Works in current version.

**Comment by dsimard** [comment]
Ok, thanks! I have to improve the installation of new versions. I'll take a look at npm!
