### ISSUE TITLE
Feature request: Use local compiler.jar?

### ISSUE THREAD

**Issue by averyvery** [dsimard/ready.js#4]
After testing ready.js for a bit, I always run into a big stack of "Error Compiling" issues. I went in and started logging the actual error, which turned out to be:

"Too many compiles performed recently"

I can wait an hour and keep going, but it would be awesome to just integrate the compiler app (found here http://code.google.com/closure/compiler/docs/gettingstarted_app.html).

**Comment by dsimard** [comment]
It's coming in the next days!

**Comment by averyvery** [comment]
Awesome! I was just trying to work it in myself, but I'm pretty bad with node. It'll be cool to see how you write it.

**Comment by dsimard** [comment]
In fact, it's another githubber. You can see his pull request here : https://github.com/dsimard/ready.js/pull/2

I just have to review and test the code and it will be ready!

**Comment by averyvery** [comment]
YUI is a good idea, but if you DID want to use a local version of Compiler, it looks like you could. Maybe this could be a future option?

**Comment by dsimard** [comment]
You know, I don't have want to be involved with java and don't want to install anything related to it... it caused me trouble in the past so I'm avoiding it... sorry! But if you want to write something code with the google compiler, I won't mind. I'll surely install a VM to test it tough...

**Comment by averyvery** [comment]
Hmm, you shouldn't need a VM — I'm on OS X and I can just run "java -jar ..." whatever from the command line to exec a script. I'll poke around and see what I can do.

**Comment by averyvery** [comment]
(I'm pretty sure YUI compressor is run the same way — java -jar yuicompressor-1.0.jar)

**Comment by dsimard** [comment]
Yeah you're right, guess I'll have to install Java... sigh...

**Comment by averyvery** [comment]
I hear you!

**Comment by dsimard** [comment]
ok, I started working on it. You can take a look at this branch : http://github.com/dsimard/ready.js/tree/2011-01-15_offline

**Comment by dsimard** [comment]
closed by 7411b75894e2330b9e7d340b5fec1b1d2e5f96ba

**Comment by dsimard** [comment]
Hi averyvery,
I completely forgot to tell you that since [ready.js v1.1.0](http://github.com/dsimard/ready.js/tree/v1.1.0), it's possible to compile offline. Just run `readyjs --installcompiler path/to/compiler.jar` and it will install the compiler for offline use.

**Comment by averyvery** [comment]
Excellent, thanks!
