### ISSUE TITLE
package.json data doesn't parse in npm 0.3.0.

### ISSUE THREAD

**Issue by joubertnel** [dsimard/ready.js#5]
Error message when trying to install:

npm info it worked if it ends with ok
npm info using npm@0.3.15
npm info using node@v0.5.0-pre
npm info fetch http://registry.npmjs.org/ready.js/-/ready.js-1.2.1.tgz
npm ERR! couldn't read package.json in /tmp/npm-1300123490834/1300123490834-0.1645010879728943/contents/package
npm ERR! Error installing ready.js@1.2.1
npm ERR! Error: Failed to parse json
npm ERR! Unexpected token ILLEGAL
npm ERR!     at jsonParseFail (/usr/local/lib/node/.npm/npm/0.3.15/package/lib/utils/read-json.js:89:11)
npm ERR!     at /usr/local/lib/node/.npm/npm/0.3.15/package/lib/utils/read-json.js:82:14
npm ERR!     at P (/usr/local/lib/node/.npm/npm/0.3.15/package/lib/utils/read-json.js:62:40)
npm ERR!     at cb (/usr/local/lib/node/.npm/npm/0.3.15/package/lib/utils/graceful-fs.js:31:9)
npm ERR!     at [object Object].<anonymous> (fs.js:86:5)
npm ERR!     at [object Object].emit (events.js:39:17)
npm ERR!     at afterRead (fs.js:882:12)
npm ERR! JSON.parse 
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse Note that package.json must be actual JSON, not
npm ERR! JSON.parse just a JavaScript object.
npm ERR! JSON.parse 
npm ERR! JSON.parse This changed in npm 0.3.0, and is not a bug in npm.
npm ERR! JSON.parse Tell the package author to fix their package.json file.
npm ERR! JSON.parse
npm ERR! System Darwin 10.6.0
npm ERR! argv { remain: [ 'ready.js' ],
npm ERR! argv   cooked: [ 'install', 'ready.js' ],
npm ERR! argv   original: [ 'install', 'ready.js' ] }

**Comment by dsimard** [comment]
Closed by 39c3faafdada5e14f24fd2f3ca90fcb4f89344ff - In fact it was the previous commit

**Comment by dsimard** [comment]
It should be OK now but I can't test with npm 0.3.x for now.

**Comment by joubertnel** [comment]
I just re-tried, and now get:

Joubert-Mac-2:~ joubert$ npm install ready.js
npm info it worked if it ends with ok
npm info using npm@0.3.15
npm info using node@v0.4.2
npm ERR! readyjslint@0.0.4 not compatible with this version of node/npm
npm ERR! Requires: {"node":">=0.1.97"}
npm ERR! You have: {"node":"v0.4.2","npm":"0.3.15"}
npm not ok

**Comment by dsimard** [comment]
Ok, I'll have a look at it.

Thanks!

**Comment by joubertnel** [comment]
Great, thanks. I'm very excited to use ready.js!

**Comment by joubertnel** [comment]
Hey - I just tried to install again and still get an error. The output talks about the error being installing optimist 0.1.3, but I notice that ready.js's package.json describes it is dependent on optimist 0.1.6 (which I can install). 

Does this mean that the npm repositories do not have the latest ready.js, and is hence trying to install an old version of ready.js that uses optimist 0.1.3 (and which is causing the install of ready.js to fail)?

**Comment by dsimard** [comment]
I had a lot of problems with npm publishing/unpublishing. It's odd because I just tried to install ready.js on another computer than my dev and it works. Optimist 0.1.6 is installed along with ready.js v1.3.0.

Could you send me your complete log?

**Comment by joubertnel** [comment]
Just tried again, and now it works!

**Comment by dsimard** [comment]
Ok, I always a little scared when a problem magically disappear but I guess it's on the side of npm and there's not so much I can do. Maybe you had an older version of the package list... I really don't know. 

Thanks!

**Comment by joubertnel** [comment]
I'll try on another machine tonight and let you know if anything useful turns up.

**Comment by dsimard** [comment]
Did it work?

**Comment by joubertnel** [comment]
Got it working.
I had to first clean the npm cache ("npm cache clean") because npm wasn't fetching the latest ready.js package.

**Comment by dsimard** [comment]
ok thanks!
