### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by oparoz** [dsimard/ready.js#6]
Just a quick feedback that it doesn't seem to work with Windows binaries of node.js.
An obvious reason is because of the use of things like

<pre>
#!/usr/bin/env node
</pre>

but there are other problems like compiling with --nojslint will compile the local folder if trying to use a config file or won't find files if trying to use a source/dest syntax.

**Comment by dsimard** [comment]
I'm pretty sure I won't do anything to make ready.js work on windows. I don't have a win ready development environment and... I could give you a lot of reasons but in fact, I really don't want to develop this OS. 

I really don't blame you, I have been a win developer for too long before but finally, I saw the light.

What you could do is fork my code and maintain the official Windows branch for it. I could also link to your code from my project to yours.

Don't worry, it's not you... it's me ;)

**Comment by oparoz** [comment]
Hehe... I don't blame you either :), but for the project I'm working on, the compiler/packager doesn't work on Unix.
I've tried alternatives, but node.js doesn't work on FreeBSD (seems like Google products rarely do) and Kubuntu is either very unstable or can't even install npm out of the box (that part worked perfectly on Windows).

I just wanted a way to easily and locally compile JS code using the Closure Compiler, so I'll try to make it work on Linux and if I can, I may take another look at the Windows side to see if I can fix it, but I wouldn't hold my breath.

**Comment by dsimard** [comment]
I won't try to make it work on Windows. I'll close the issue for now.
