### ISSUE TITLE
[Kubuntu] Cannot install compiler locally

### ISSUE THREAD

**Issue by oparoz** [dsimard/ready.js#7]
I've tried to install ready.js using npm, but instead of having binaries in /usr/local, they end up in a local 'node_modules' folder.

I can then launch the command and it can compile files, however, when trying to install the compiler locally (I don't fancy sending all my files on the Internet), it fails with this:
ERROR : Installing a compiler is available only with a NPM installation. Run `npm install ready`.

I suspect that the error message meant ' npm install ready.js', but still that's what I did and it still doesn't work.

**Comment by robbles** [comment]
I used `npm install -g ready.js` to get around this. Installing tools globally with npm adds the binaries to a directory in the path.

**Comment by dsimard** [comment]
The old package (v1.0.0) was called "ready". I'll try to delete it from the repository.

Thanks!
