### ISSUE TITLE
Integration of vows & colorize output

### ISSUE THREAD

**Issue by schakko** [dsimard/ready.js#9]
Hey,
I made a quick hack (it's really a hack) for integrating vows into ready.js.
See https://github.com/schakko/ready.js/commit/cbeee9f762ec1915e005ca8b440cfa28af58c2ea

Greetings,
Schakko

**Comment by dsimard** [comment]
Ok, I'll have a look at it

**Comment by dsimard** [comment]
I didn't add vows for now and I colorized the output in the logger.
